language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

addons:
 apt:
  packages:
  - rabbit

services:
  - rabbitmq

install:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - cpanm -n -q Test::More Test::Script
  - perl Build.PL && yes "" | ./Build installdeps --cpan_client 'cpanm -n -q'

env:
  global:
    - RABBIT_HOSTNAME=127.0.0.1
    - RABBIT_USERNAME=guest
    - RABBIT_PASSWORD=guest
    - RABBIT_SERVERNAME=$(sudo hostname)
    - RABBIT_1_RNAME=rabbit
    - RABBIT_1_MGT_PORT=15672

script:
  - ./Build test --verbose=1
